task: detection

num_classes: 2
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./configs/dataset/train2017/
    ann_file: ./configs/dataset/annotations/train_labels.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./configs/dataset/val2017/
    ann_file: ./configs/dataset/annotations/val_labels.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 4
  num_workers: 1
  drop_last: False
