__include__: [
  '/home/uvll/Desktop/hyuk/rtdetr/rtdetr_pytorch/rtdetrv2_pytorch/datasets/Dsg/coco_detection.yml',
  '/home/uvll/Desktop/hyuk/rtdetr/rtdetr_pytorch/rtdetrv2_pytorch/configs/runtime.yml',
  '/home/uvll/Desktop/hyuk/rtdetr/rtdetr_pytorch/rtdetrv2_pytorch/configs/rtdetrv2/include/dataloader.yml',
  '/home/uvll/Desktop/hyuk/rtdetr/rtdetr_pytorch/rtdetrv2_pytorch/configs/rtdetrv2/include/optimizer.yml',
  '/home/uvll/Desktop/hyuk/rtdetr/rtdetr_pytorch/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml',
]


output_dir: /home/uvll/Desktop/hyuk/rtdetr/RT-DETR/rtdetr_pytorch/rtdetrv2_pytorch/output/rtdetrv2_dsg_star_galaxy_2nd



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

weight: /home/uvll/Desktop/hyuk/rtdetr/RT-DETR/rtdetr_pytorch/rtdetrv2_pytorch/weights/rtdetrv2_r50vd_6x_coco_ema.pth # manually added